// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpwdsxV-bvNHyIHgYUzqfjL3dF_1XBAJA',
    appId: '1:267011302063:web:1faebed72386e4ca3a2a5a',
    messagingSenderId: '267011302063',
    projectId: 'test1-37071',
    authDomain: 'test1-37071.firebaseapp.com',
    storageBucket: 'test1-37071.appspot.com',
    measurementId: 'G-ZG1EJXW8CS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD908StEu9AD19VcBXVZ7u1qB7fIVkbf5g',
    appId: '1:267011302063:android:10c07bc8c6f2a1123a2a5a',
    messagingSenderId: '267011302063',
    projectId: 'test1-37071',
    storageBucket: 'test1-37071.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2JXpsL6yzbKOgRd_dLt80OgHt7GzJCg8',
    appId: '1:267011302063:ios:5e5cd46c4154a3003a2a5a',
    messagingSenderId: '267011302063',
    projectId: 'test1-37071',
    storageBucket: 'test1-37071.appspot.com',
    iosBundleId: 'com.example.firebasecurd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2JXpsL6yzbKOgRd_dLt80OgHt7GzJCg8',
    appId: '1:267011302063:ios:5e5cd46c4154a3003a2a5a',
    messagingSenderId: '267011302063',
    projectId: 'test1-37071',
    storageBucket: 'test1-37071.appspot.com',
    iosBundleId: 'com.example.firebasecurd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpwdsxV-bvNHyIHgYUzqfjL3dF_1XBAJA',
    appId: '1:267011302063:web:7ab9572f9fbb58353a2a5a',
    messagingSenderId: '267011302063',
    projectId: 'test1-37071',
    authDomain: 'test1-37071.firebaseapp.com',
    storageBucket: 'test1-37071.appspot.com',
    measurementId: 'G-D77JLNQV57',
  );
}
